### ISSUE TITLE
[Tjeneste] Komponenten Dokumentasjonskrav

### ISSUE THREAD

**Issue by terjesyl** [Informasjonsforvaltning/fdk-portal#1376]
Vise listen av Dokumentasjonskrav og Dokumentasjon

## Tilsvarer felt
* `cpsv:hasInput` / "Har Dokumentasjonskrav" i CPSV.
* `hasInput` i JSON-respons.

I tillegg skal dokumentasjon tas med fra:
* `cpsv:hasInput` i klassen Tjenestekanal i CPSV
* `hasInput` i fra objektene i `hasChannel`-feltet i JSON.

## Skille mellom visning av typen Datasett og typen Evidence
Hvis en entry peker til et datasett, vis som Datasett-boks (se bilde).
`rdfType` bestemmer dette.
`rdfType` er av typen `"http://www.w3.org/ns/dcat#Dataset"`, `"http://data.europa.eu/m8g/Evidence"` eller `"UNKNOWN"`.

## TODOs
- [ ] Liste av Dokumentasjonskrav/`Evidence`

### Fra `hasInput`:
- [ ] Visning av Dokumentasjonskrav (rdfType Evidence)
  - [ ] Navn: `name` (obligatorisk)
  - [ ] Type: `dctType` (eks: "Attest")
  - [ ] Beskrivelse: `description`
  - [ ] Aksepterte språk: `language`
  - [ ] Relatert informasjon: `page`
  - [ ] Tjenestekanal: ? intern lenke?
- [ ] Visning av Dokumentasjonskrav (rdfType Datasett)
  - [ ] Navn på datasett (usikker på attributt-navnet, muligens "title" eller "dctTitle") + lenke
  - [ ] Beskrivelse

### Fra `hasChannel[n].hasInput`:
- [ ] Navn `name`
- [ ] Tittel på tjenestekanal (+ intern lenke)

![bilde](https://user-images.githubusercontent.com/108797958/205938570-97d6057f-f509-4f1f-83cb-0b11435d261c.png)

Depends on
- [x] #1364
- [x] #1362 
- [x] #1363 
- [x] https://github.com/Informasjonsforvaltning/fdk-rdf-parser/issues/171
- [ ] `hasInput` fra Channel: https://github.com/Informasjonsforvaltning/fdk-rdf-parser/issues/170

**Comment by KurtStian** [comment]
@terjesyl Har dokumentasjonkrav (has input) kan knyttes til en tjenestekanal når kravet er spesifikk for den aktuelle tjenestekanalen. Dokumentasjonskrav som er uavhengig av tjenestekanal bør knyttes til tjenesten.

Her kan vi få tilfeller der samme dokumentasjon er knyttet til flere tjenestekanaler og/eller tjenestekanaler og direkte til tjenesten. 

Hvis det er flere tjenestekanaler som har samme dokumentasjon (samme identifikator) så kan det vel løses ved å oppgi navnet på de kanalene som referer til samme dokumentasjon (jf. eks. "Viktig erklæring)

Hvis tjenestekanal(er) og tjenesten refere til samme krav (samme identifikator) skal kravet vises to ganger (og dette vil forhåpentligvis medføre at kildene rydder opp).
