### ISSUE TITLE
Ny startside for Felles Datakatalog

### ISSUE THREAD

**Issue by lillelars** [Informasjonsforvaltning/fdk-portal#145]
@oyvindis Dele opp i oppgaver + estimere ulike deler

- [x] Toppmeny, 9t

- [x] Oppsett ny responsiv forside, endre ruting av undersider osv, 3t

- [x] "Sist publsiert", 3t

- [x] Endepunkt for "Aktuelt", koble mot endepunkt og visning på forsiden, 5t

- [x] Twitterfeed, 9t

- [x] Søkeboks og inngangsknapper, 9t (responsive knapper, med statisk link uten søkeparametre)

- [x] Logo går nå til ny startside, 'as is', den skal fortsatt gå til rot på domenet, 0t

Lenke til design:
https://eggedosis.github.io/fdk-design/redirects/portal/home/home-default.html

Lenke til mobildesign:
https://eggedosis.github.io/fdk-design/redirects/portal/home/mobile-home-default.html

Hentet fra behov:
https://github.com/Informasjonsforvaltning/behov/issues/420

**Comment by oyvindis** [comment]
@lillelars: man kan utføre søk på forsiden, skal vi si at den gjør et søk og tar brukeren direkte til 'alle-fanen', dvs. forsiden viser alltid bare de siste 5 publiserte?

**Comment by lillelars** [comment]
klar til akseptanse. Setter denne på deg @joebrreg
