### ISSUE TITLE
Epic: Oppdatere fdk portal

### ISSUE THREAD

**Issue by KjerstiSteien** [Informasjonsforvaltning/fdk-portal#1889]
### Epic beskrivelse
I forbindelse med overgang til fdk-search-service, har vi behov for å endre api-integrasjonen i FDK-portal

### Dette innebærer
- [x] Informasjonsforvaltning/fdk-portal#1894
- [x] Informasjonsforvaltning/fdk-portal#1895
- [x] Informasjonsforvaltning/fdk-portal#1896
- [x] Informasjonsforvaltning/fdk-portal#1897
- [x] #1903
- [x] Informasjonsforvaltning/fdk-issue-tracker#889
- [x] Informasjonsforvaltning/fdk-portal#1899
    - https://github.com/Informasjonsforvaltning/fdk-reference-data/issues/184
- [x] Informasjonsforvaltning/fdk-rss-atom-feed#31

### Sjekkliste (Sjekk av etter issue er laget)

- [ ] Lagt til label(s)
- [ ] Lagt i utviklingsbrettet (Project)
