### ISSUE TITLE
Extinguish - "Something went wrong"

### ISSUE THREAD

**Issue by lillelars** [Informasjonsforvaltning/fdk-portal#794]
Hva kan vi gjøre med denne?
#### Vi må komme opp med forslag/tiltak på mulige løsninger for å håndtere og/eller fikse denne type feil. (Se kommentar under)
NB! Kom opp med t-skjorte størrelse på estimatter på oppgaver/tiltak

- [ ] Forbedret testdekning - f.eks automatisk testing i prod (web driver tester?)

- [ ] ende-til-ende tester m/ monitorering i prod?

- [ ] monitorering i prod? 
vurdere frontend - monitoreringsverktøy som Sentry ?

- [ ] Testdekning i rdfparser ?

- [ ] error-boundaries på ulike elementer for å rendre deler av siden

- [ ] cache - controll på requestene ? Se om vi setter korrekt expiry date på våre javascript filer. Fungerer dette som forventet?

- [ ] Forbedre looken på feilsiden "Something went wrong"
Se design:
https://eggedosis.github.io/fdk-design/redirects/portal/other/500.html

**Comment by oyvindis** [comment]
Det som gir mest verdi på kortest tid:
Error-boundaries på ulike elementer for å rendre deler av siden (M)
Legge til logging til GCP fra error-boundary
Forbedre looked på heilsiden “Something went wrong” (S)

Videre kan vi proaktivt oppdage feil i prod før brukerne:
Automatisert “semantic monitoring” i prod (L):
	- alle detaljsider
	- bla gjennom alle søkesider
	

Flere kvalitetsforbedringer vi på sikt kan gjøre i kode:
Ryddejobb i alle våre typer - (L)
Refaktorere kode til TS - bruker typer overalt (L/XL)

**Comment by lillelars** [comment]
@joebrreg klar til akseptanse
